FROM alpine
RUN	apk update apk upgrade  && apk add vim
ENTRYPOINT ["vim"]

#docker build -t ex00 .
#docker run --rm -ti ex00
#https://docs.docker.com/engine/reference/builder/#cmd
#https://thenewstack.io/docker-basics-how-to-use-dockerfiles/
